const fs=require('fs'),cp=require('child_process');
const dir='public/paintings';
const files=fs.readdirSync(dir).filter(f=>/\.jpe?g$/i.test(f)).sort();
const data={};
for(const f of files){
  try{
    const o=cp.execSync(`sips -g pixelWidth -g pixelHeight "${dir}/${f}"`).toString();
    const w=+o.match(/pixelWidth: (\d+)/)[1], h=+o.match(/pixelHeight: (\d+)/)[1];
    data[f]={w,h};
  }catch(e){}
}
fs.writeFileSync('src/paintingsData.js','// AUTO-GENERATED by scripts-measure.cjs — pixel dims drive dynamic sizing\nexport default '+JSON.stringify(data,null,0)+'\n');
console.log('measured',Object.keys(data).length,'paintings -> src/paintingsData.js');
